# -*- coding: utf-8 -*-
"""Fruad_Transaction_Data_Gather.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/189TgvLRo9PmDY8Fru_CfqNkqX-JUk-zS
"""

#!pip install cassandra-driver

#from google.colab import drive
#drive.mount('/content/drive')

import pandas as pd
import numpy as np

from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider

cloud_config= {
        'secure_connect_bundle': r'C:/Users/Admin/PycharmProjects/Fruad_Transaction/secure-connect-fraud-transaction-detection.zip'
}
auth_provider = PlainTextAuthProvider('oMKprOmBBlDSxhSkvZfEQpMW', 'eKOK,pzouPRvU9bhCP7bULP0hT8+_X5Of,T_O0XTuPWi00ABBm8xtbI.50w4fkgWRhJ5nTNZtC,+nEjtmeM93d2WKEqQ.U+d0jWbZ6QUIpB.drblyn3hsCsSawAPPZm4')
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()
session.set_keyspace("121fraud121")
session.default_fetch_size=None

count=0
results = session.execute("SELECT * FROM creditcard",timeout=None)
for i in results:
    count+=1
    credit_data=pd.DataFrame(results)

credit_data.head()

credit_data = pd.DataFrame(credit_data)
# saving the dataframe
credit_data.to_csv('credit_data.csv')
